# -*- coding: utf-8 -*-
"""gs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d3z4mdwJpgjS1Yrv93Y2Co7qkcVjKLwP

Gerador de Senhas
"""

#importando bibliotecas para desenvolver um gerador de senhas
import random
import string

#Atribuição de tamanho da senha
tamanho = int(input('Digite o tamanho da senha que você deseja gerar :'))

#Atribuição de letras, números e caracteres especiais
chars = string.ascii_letters + string.digits + '!@#$&*ç()_-=,.:/?'

#Variável para armazenar a senha gerada e impressão
rnd = random.SystemRandom() #os.urandom

print(''.join(rnd.choice(chars) for i in range (tamanho)))