# -*- coding: utf-8 -*-
"""threads.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13KyiJJ1vVW46Wtu8rNMocA6fbQ3Sl1iL
"""

#importação da classe Thread a partir do módulo threading para realização do multithreading
from threading import Thread
import time

#Criação de função os dois carros começam com zero no trajeto
def carro(velocidade, piloto):
  trajeto = 0
  while trajeto <= 100:
    trajeto+=velocidade
    time.sleep(0.5)
    print('Carro: ', piloto, trajeto)
    print('Piloto(a): {} Km: {} \n'.format(piloto, trajeto))

#Criação de objetos
t_carro1 = Thread(target=carro, args=[1, 'Mirian'])
t_carro2 = Thread(target=carro, args=[2, 'Python'])

t_carro1.start()
t_carro2.start()